version: 2
updates:
  # Enable version updates for npm (CLI package)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(dev-deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "cli"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "*test*"
          - "*mock*"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "*test*"
          - "*mock*"

  # Enable version updates for npm (VSCode Extension)
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(extension-deps):"
      prefix-development: "chore(extension-dev-deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "vscode-extension"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "*test*"
          - "*mock*"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "*test*"
          - "*mock*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions):"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"