name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm

    - name: Install workspace dependencies
      run: npm ci

    - name: Create CLI tarball for extension dependencies
      run: npm run package:cli

    - name: Install extension dependencies with CLI package
      run: cd vscode-extension && npm install ../dipjyotimetia-postmortem-*.tgz

    - name: Install Xvfb for headless testing
      run: sudo apt-get install -y xvfb
      
    - name: Run linter (all packages)
      run: npm run lint
      
    - name: Run tests (all packages)
      run: xvfb-run -a npm run test:all
      env:
        DISPLAY: ":99.0"
      
    - name: Run test coverage
      run: xvfb-run -a npm run test:coverage
      env:
        DISPLAY: ":99.0"
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install workspace dependencies
      run: npm ci

    - name: Create CLI tarball for extension dependencies
      run: npm run package:cli

    - name: Install extension dependencies with CLI package
      run: cd vscode-extension && npm install ../dipjyotimetia-postmortem-*.tgz
      
    - name: Build packages with proper dependencies
      run: npm run build
      
    - name: Test conversion with example collection
      run: npm run convert
      
    - name: Verify generated tests and extension build
      run: |
        test -f test-output/setup.ts
        test -f vscode-extension/dist/extension.js
        # Verify the dependency is available (workspace or local)
        cd vscode-extension && npm ls @dipjyotimetia/postmortem
        echo "✅ All builds successful"
