name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm

    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Run test coverage
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install CLI dependencies
      run: npm ci
      
    - name: Build CLI
      run: npm run build
      
    - name: Test conversion with example collection
      run: npm run convert
      
    - name: Verify generated tests
      run: |
        test -f test-output/setup.ts
        echo "✅ Test generation successful"

  extension-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install CLI dependencies
      run: npm ci
      
    - name: Build CLI
      run: npm run build
      
    - name: Install extension dependencies
      working-directory: ./vscode-extension
      run: npm ci
      
    - name: Compile extension
      working-directory: ./vscode-extension
      run: npm run compile
      
    - name: Run extension linting
      working-directory: ./vscode-extension
      run: npm run lint
