name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: npm

    - name: Install workspace dependencies
      run: npm ci
      
    - name: Run linter (all packages)
      run: npm run lint
      
    - name: Run tests (all packages)
      run: npm run test:all
      
    - name: Run test coverage
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install workspace dependencies
      run: npm ci
      
    - name: Build all packages
      run: npm run build
      
    - name: Test conversion with example collection
      run: npm run convert
      
    - name: Verify generated tests and extension build
      run: |
        test -f test-output/setup.ts
        test -f vscode-extension/dist/extension.js
        echo "✅ All builds successful"
